const state={project:null,file:null,terminalHeight:170,aiMode:localStorage.getItem('agape.ai.mode')||'auto'};
const $=id=>document.getElementById(id);
async function api(path,method='GET',body=null){const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):null});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||`HTTP ${r.status}`);return j}
function logTerminal(text){$('terminalOutput').textContent += `\n${text}`;$('terminalOutput').scrollTop=$('terminalOutput').scrollHeight}
function textRow(title,detail,badge=''){const row=document.createElement('div');row.className='status-row';const box=document.createElement('div');const strong=document.createElement('strong');strong.textContent=title;box.appendChild(strong);if(detail){const small=document.createElement('small');small.textContent=detail;box.appendChild(document.createElement('br'));box.appendChild(small)}row.appendChild(box);if(badge){const b=document.createElement('span');b.className='badge';b.textContent=badge;row.appendChild(b)}return row}
async function loadRecent(){const j=await api('/api/projects');const box=$('recentProjects');box.innerHTML='';j.projects.forEach(p=>{const row=document.createElement('div');row.className='recent-item';const info=document.createElement('span');const name=document.createElement('strong');name.textContent=p.name;const path=document.createElement('small');path.textContent=p.path;info.append(name,document.createElement('br'),path);const button=document.createElement('button');button.textContent='Open';button.onclick=()=>openProject(p.path);row.append(info,button);box.appendChild(row)})}
async function openProject(path){const j=await api('/api/projects/open','POST',{path});state.project=j.project;$('projectLabel').textContent=state.project.name;$('homeView').classList.add('hidden');$('workspaceView').classList.remove('hidden');await loadFiles()}
async function createProject(){const name=prompt('Project name');if(!name)return;const j=await api('/api/projects/create','POST',{name});await openProject(j.project.path)}
async function loadFiles(){const j=await api('/api/files/list','POST',{project_path:state.project.path});const box=$('fileList');box.innerHTML='';j.files.forEach(f=>{const b=document.createElement('button');b.textContent=f;b.onclick=()=>openFile(f);box.appendChild(b)})}
async function openFile(path){const j=await api('/api/files/read','POST',{project_path:state.project.path,path});state.file=path;$('activeTab').textContent=path;$('editor').value=j.content}
async function saveFile(){if(!state.project||!state.file)return;await api('/api/files/write','POST',{project_path:state.project.path,path:state.file,content:$('editor').value});logTerminal(`SAVE=PASS ${state.file}`)}
async function runTerminal(){if(!state.project){logTerminal('Open a project first.');return}const raw=$('terminalInput').value.trim();if(!raw)return;const argv=raw.match(/(?:[^\s"]+|"[^"]*")+/g)?.map(x=>x.replace(/^"|"$/g,''))||[];logTerminal(`> ${raw}`);try{const j=await api('/api/terminal/run','POST',{project_path:state.project.path,argv});if(j.stdout)logTerminal(j.stdout.trimEnd());if(j.stderr)logTerminal(j.stderr.trimEnd());logTerminal(`EXIT=${j.exit_code}`)}catch(e){logTerminal('ERROR='+e.message)}}
async function askAi(){if(!state.project)return;const message=$('aiInput').value.trim();if(!message)return;const context=state.file?`Current file: ${state.file}\n${$('editor').value}`:'';$('aiMessages').textContent+=`You: ${message}\n`;try{let plan=null;try{plan=await api('/api/tools/plan','POST',{project_path:state.project.path,task:message,mode:state.aiMode})}catch(_){}if(plan)$('aiRouteNote').textContent=`recommended: ${plan.tool}`;const j=await api('/api/ai/chat','POST',{project_path:state.project.path,message,task:'code',context,mode:state.aiMode});$('aiMessages').textContent+=`Agape (${j.provider}/${j.model}): ${j.reply}\n`;$('aiRouteNote').textContent=`${plan?'recommended '+plan.tool+' · ':''}${j.tier}; fallbacks ${j.fallbacks_used}`;await refreshAi()}catch(e){$('aiMessages').textContent+=`AI ERROR: ${e.message}\n`}}
async function runAider(){if(!state.project){logTerminal('AIDER=BLOCKED Open a project first.');return}const task=$('aiInput').value.trim();if(!task){logTerminal('AIDER=BLOCKED Enter a development task first.');return}try{const plan=await api('/api/tools/plan','POST',{project_path:state.project.path,task,mode:state.aiMode});$('aiRouteNote').textContent=`recommended: ${plan.tool}`;if(plan.tool!=='aider'){logTerminal(`AIDER=NOT_SELECTED ${plan.reason}`);return}logTerminal(`AIDER=START MODEL=${plan.aider_model}`);const result=await api('/api/tools/aider/run','POST',{project_path:state.project.path,task,mode:state.aiMode,timeout:600});logTerminal(`AIDER=${result.ok?'PASS':'FAIL'} EXIT=${result.exit_code} CHANGED=${result.changed_files.length}`);if(result.stdout)logTerminal(result.stdout.trimEnd());if(result.stderr)logTerminal(result.stderr.trimEnd());await loadFiles()}catch(e){logTerminal('AIDER=FAIL '+e.message)}}
async function refreshAi(){try{const [status,free]=await Promise.all([api('/api/ai/status'),api('/api/ai/free-models?task=code')]);const candidates=status.providers.filter(p=>p.ok&&p.models.length);const local=candidates.find(p=>p.tier==='local');const freeOnline=candidates.find(p=>p.tier==='free-online');let label=`AI: ${state.aiMode[0].toUpperCase()+state.aiMode.slice(1)}`;if(state.aiMode==='auto'&&local)label+=` (${local.models[0]})`;else if(state.aiMode==='free'&&free.models.length)label+=` (${free.models[0].model})`;else if(state.aiMode==='local'&&local)label+=` (${local.models[0]})`;else if(freeOnline)label+=' (free online available)';else label+=' (offline)';$('aiStatus').textContent=label;renderAiManager(status,free)}catch{$('aiStatus').textContent='AI: '+state.aiMode+' (error)'}}
function renderAiManager(status,free){const providers=$('providerList');providers.innerHTML='';status.providers.forEach(p=>providers.appendChild(textRow(`${p.provider} · ${p.tier}`,p.ok?`${p.model_count} model(s)${p.credential_configured?' · generation configured':' · generation credential not configured'}`:(p.error||'unavailable'),p.ok?'PASS':'OFFLINE')));const models=$('freeModelList');models.innerHTML='';if(!free.models.length)models.appendChild(textRow('No current free models discovered','Refresh when internet access is available.','INFO'));free.models.slice(0,12).forEach((m,i)=>models.appendChild(textRow(`${i+1}. ${m.name}`,`${m.model} · context ${m.context_length||'unknown'} · score ${m.score} · ${m.reason}`,'FREE')))}
async function openAiManager(){$('aiMode').value=state.aiMode;$('aiDialog').showModal();await refreshAi();await loadConnectionHistory()}
async function testConnections(){try{const r=await api('/api/connections/test','POST',{generation:false});logTerminal(`AI_CONNECTION_GATE=${r.ok?'PASS':'FAIL'}`);await loadConnectionHistory();await refreshAi()}catch(e){logTerminal('AI_CONNECTION_GATE=FAIL '+e.message)}}
async function loadConnectionHistory(){try{const j=await api('/api/connections/tests?limit=30');const box=$('connectionHistory');box.innerHTML='';j.tests.slice(0,30).forEach(x=>box.appendChild(textRow(`${x.provider}${x.model?' / '+x.model:''}`,`${x.source} · ${x.detail} · ${x.created_at}`,x.status)))}catch(e){$('connectionHistory').textContent=e.message}}
async function showPassed(){const j=await api('/api/quality/status');$('passedSummary').textContent=`${j.passed_count}/${j.total} verified parts passed. ${j.open_count} remain open/not published.`;const box=$('passedList');box.innerHTML='';j.passed.forEach(x=>box.appendChild(textRow(`${x.item_id} · ${x.title}`,`${x.area} · ${x.detail}${x.passed_at?' · '+x.passed_at:''}`,'PASS')));const open=$('openIssuesList');open.innerHTML='';j.open.forEach(x=>open.appendChild(textRow(`${x.item_id} · ${x.title}`,`${x.area} · ${x.detail||'Awaiting verified test evidence'}`,x.status)));$('passedDialog').showModal()}
async function loadAiderStatus(){try{const j=await api('/api/tools/aider/status');const a=j.aider;$('aiderStatusText').textContent=a.ready?`Ready · ${a.version}`:(a.installed?`Installed but not ready · ${a.detail}`:'Not installed · optional · run INSTALL-AIDER.cmd from the Studio release folder');$('runAiderBtn').disabled=!a.ready;return a}catch(e){$('aiderStatusText').textContent='Status error · '+e.message;$('runAiderBtn').disabled=true;return null}}
async function showExtensions(){const j=await api('/api/extensions');$('extensionsList').innerHTML='';j.extensions.forEach(x=>$('extensionsList').appendChild(textRow(x.name,`${x.description||''} · ${(x.actions||[]).join(', ')}`,'INSTALLED')));$('extensionsDialog').showModal();await loadAiderStatus()}
$('newProjectBtn').onclick=createProject;$('openProjectBtn').onclick=()=>{const p=prompt('Full project folder path');if(p)openProject(p)};$('saveFileBtn').onclick=saveFile;$('terminalRun').onclick=runTerminal;$('terminalInput').addEventListener('keydown',e=>{if(e.key==='Enter')runTerminal()});$('askAiBtn').onclick=askAi;$('runAiderBtn').onclick=runAider;$('aiInput').addEventListener('keydown',e=>{if(e.key==='Enter')askAi()});$('extensionsBtn').onclick=showExtensions;$('checkAiderBtn').onclick=loadAiderStatus;$('settingsBtn').onclick=()=>$('settingsDialog').showModal();$('aiStatus').onclick=openAiManager;$('passedBtn').onclick=()=>showPassed().catch(e=>logTerminal('PASSED_MENU_ERROR='+e.message));$('refreshAiBtn').onclick=refreshAi;$('testConnectionsBtn').onclick=testConnections;$('aiMode').onchange=e=>{state.aiMode=e.target.value;localStorage.setItem('agape.ai.mode',state.aiMode);refreshAi()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
let dragging=false;$('terminalHandle').addEventListener('mousedown',()=>dragging=true);window.addEventListener('mouseup',()=>dragging=false);window.addEventListener('mousemove',e=>{if(!dragging)return;const h=Math.max(70,Math.min(window.innerHeight*.7,window.innerHeight-e.clientY));$('terminalPanel').style.height=h+'px';document.querySelectorAll('.home-view,.workspace').forEach(x=>x.style.height=`calc(100vh - ${h+48}px)`)})
let collapsed=false;$('terminalToggle').onclick=()=>{collapsed=!collapsed;$('terminalPanel').style.height=collapsed?'70px':'170px';$('terminalToggle').textContent=collapsed?'Expand':'Collapse'};
loadRecent().catch(console.error);refreshAi();
